package model;

public enum Tokens {
    tk_inicio,
    tk_fin,
    tk_entero,
    tk_numeroEntero,
    tk_flotante,
    tk_numeroFlotante,
    tk_leer,
    tk_imprimir,
    tk_sum,
    tk_res,
    tk_mul,
    tk_div,
    tk_variable,
    tk_coma,
    tk_igual,
    tk_constante,
    tk_puntoComa,
    tk_punto,
    tk_identificador,
    tk_parentesisAbre,
    tk_parentesisCierra,
    tk_corcheteAbre,
    tk_corcheteCierra,
    tk_llaveAbre,
    tk_llaveCierra,
    tk_decimal,
    espacio,
    ERROR,
}